<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="html_model" nsURI="www.html_model.cm" nsPrefix="html_model">
  <eClassifiers xsi:type="ecore:EClass" name="TextElement" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph" eSuperTypes="#//TextContainer #//ListItemElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Navigation" eSuperTypes="#//ContainableTextElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupedItems" upperBound="-1"
        eType="#//ListElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainableTextElement" abstract="true"
      eSuperTypes="#//PageContent #//TextElement #//ListItemElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableCell" eSuperTypes="#//TextContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignement" eType="#//TableCellAlignement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="span" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TableCellAlignement">
    <eLiterals name="LEFT"/>
    <eLiterals name="RIGHT" value="1"/>
    <eLiterals name="CENTER" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//PageContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UrlBasedLink" abstract="true" eSuperTypes="#//CompositeTextElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableHead" eSuperTypes="#//TableSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ListItemElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//CompositeTextElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeTextElement" abstract="true"
      eSuperTypes="#//ContainableTextElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTextElements" upperBound="-1"
        eType="#//TextElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListElement" abstract="true" eSuperTypes="#//PageContent #//ListItemElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//ListItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//PageContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tablesections" upperBound="-1"
        eType="#//TableSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableBody" eSuperTypes="#//TableSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Title" eSuperTypes="#//TextContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//UrlBasedLink"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextContainer" abstract="true" eSuperTypes="#//PageContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textElements" upperBound="-1"
        eType="#//TextElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section" eSuperTypes="#//PageContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pagecontent" upperBound="-1"
        eType="#//PageContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableSeparator" eSuperTypes="#//TableSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnorderedList" eSuperTypes="#//ListElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedList" eSuperTypes="#//ListElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListItemElement" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//UrlBasedLink"/>
  <eClassifiers xsi:type="ecore:EClass" name="PageContent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="section" upperBound="-1"
        eType="#//Section" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//TableCell" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableSection" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//TableRow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//TextElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
